var GET_ACCESS_TOKEN = "GET_ACCESS_TOKEN";
var SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
var GET_CACHE_ACCESS_TOKEN = "GET_CACHE_ACCESS_TOKEN";
var SET_CACHE = "SET_CACHE";

var GITHUB_LINK_PATTERN = /^https?:\/\/github.com\/([A-Za-z0-9-]+?)\/([A-Za-z0-9-]+?)\/?$/;
